### ISSUE TITLE
Tips on running experiments

### ISSUE THREAD

**Issue by IvanAnishchuk** [jvhs0706/zkllm-ccs2024#7]
Hi,

Thanks for the great work you're doing. My team is exploring various ZK-ML proof systems for an open-source protocol and yours looks very promising. I'm currently conducting a simple attempt to measure inference and proof generation performance on different hardware (using the default LLaMa-2 for starters to verify the research paper numbers) and then plan to explore ways to optimise and adapt the system for other models and maybe create some PoC project to demonstrate the capabilities of the approach.

So far I managed to install the dependencies, download the model files, and followed the steps for generating commitment but I'm having trouble with the next steps. I understand that input should be pytorch tensors converted to integers saved into numpy format, is there some utility or instructions for handling that conversion (like, for example, if I have a set of text prompts and want to generate input files for each of them)? And, vice versa, a way to convert output into a demoable text response.

Sorry if it's a rookie question, just want to be sure I understand everything and thanks in advance! If you have any other tips and details it would be most appreciated as well. 

Ivan.

**Comment by jvhs0706** [comment]
Hi Ivan,

Thank you for your recognition and interest. Based on the questions from you and others, I have a few quick tips to mention:

1. The current version works on the embeddings only.
2. The demo has been vastly modified from the pre-refinement versions, and combines the of loading, computing, committing, proving, verifying, etc. (and their overheads of course), as a complete demonstration of the functionalities.
3. Make sure that it's indeed running correctly on your GPUs 😄 

Please [contact me via email or otherwise](https://cs.uwaterloo.ca/~h299sun/#contact) for further discussion, as I would also want to learn more about your project
